### ISSUE TITLE
Implement `MockProver` 

### ISSUE THREAD

**Issue by davidnevadoc** [akinovak/zero-over-k#16]
Implement a mock prover for easy circuit testing. The mock prover does not  generate a proof, it just checks that the gate, copy and lookup constraints are satisfied. 

The commented out sanity check used in `prove()` can be used as a starting point (see https://github.com/zero-over-k/zero-over-k/blob/main/src/lib.rs#L483-L562 ). It needs to be adapted and expanded with the copy and lookup checks. 

**Tasks**
- [x] Basic version (just VO checks)
- [ ] Add permutation check
- [ ] Add lookup check
